<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/Round%20Robin%20Arbiter/RoundRobin_PrevOp_16bit_git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# only for Google Colab compatibiity
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.11.0


In [27]:
%matplotlib notebook

In [28]:
df = pd.read_csv('round_robin_16.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("round_robin_16.txt",sep=" ",header=None, dtype=col_str_dic)
x_gen = df.iloc[:,0]
y_gen = df.iloc[:,1]
x_samples=[]
y_samples=[]
for x in x_gen:
  temp = list(x)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  x_samples.append(temp_list)
for y in y_gen:
  # print(y)
  temp = list(y)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  y_samples.append(temp_list)

In [29]:
x_s = []
y_s = []
k = len(x_samples)
temp =[]
temp.append(x_samples[0])
temp.append(x_samples[0])
x_s.append(temp)
for i in range(1,k):
  temp = []
  temp.append(y_samples[i-1])
  temp.append(x_samples[i])
  x_s.append(temp)
y_s = y_samples

In [30]:
len(y_s)

154924

In [31]:
x_temp = np.array(x_s) # 16 inputs
x_t = []
for a in x_temp:
  temp = a.flatten()
  x_t.append(temp)
x = np.array(x_t)
print(x[1])
y_temp = np.array(y_s) # 16 inputs
y_t = []
for a in y_temp:
  temp = a.flatten()
  y_t.append(temp)
y = np.array(y_t)
print(y[1])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)
#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [33]:
#ANN1
#model = models.Sequential(name='Parity_checker')
#model.add(layers.Input(shape=(32,), name='input'))
#model.add(layers.Dense(units=32,activation=activations.relu, name='hidden1'))
## model.add(layers.Dense(units=3, activation=activations.sigmoid, name='hidden2'))
#model.add(layers.Dense(units=1, activation=activations.sigmoid, name='output'))

#add the layers
#ANN2:0.99 accuracy
# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(64, input_dim=32, activation='relu'))
# model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# ANN3:0.99 accuracy
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=32, activation='relu'))
# model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(24, activation='relu'))
# model.add(tf.keras.layers.Dense(24, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(32, input_dim=16, activation='relu'))
# # model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='relu'))
# model.add(tf.keras.layers.Dense(8, activation='relu'))
# model.add(tf.keras.layers.Dense(4, activation='relu'))
# model.add(tf.keras.layers.Dense(2, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 32)                1056      
                                                                 
 dense_7 (Dense)             (None, 16)                528       
                                                                 
 dense_8 (Dense)             (None, 16)                272       
                                                                 
Total params: 1,856
Trainable params: 1,856
Non-trainable params: 0
_________________________________________________________________


In [34]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [35]:
model.fit(x_train, y_train, epochs=100)
score = model.evaluate(x_test, y_test, verbose=2)

Epoch 1/100
3389/3389 [==============================] - 12s 3ms/step - loss: 0.0268 - accuracy: 0.7051
Epoch 2/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0088 - accuracy: 0.9056
Epoch 3/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0060 - accuracy: 0.9361
Epoch 4/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0047 - accuracy: 0.9446
Epoch 5/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0040 - accuracy: 0.9475
Epoch 6/100
3389/3389 [==============================] - 10s 3ms/step - loss: 0.0037 - accuracy: 0.9488
Epoch 7/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0035 - accuracy: 0.9501
Epoch 8/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0033 - accuracy: 0.9524
Epoch 9/100
3389/3389 [==============================] - 11s 3ms/step - loss: 0.0032 - accuracy: 0.9535
Epoch 10/100
3389/3389 [==============================] - 11s 3m

In [36]:
#Comparing the data and writing into the file ( input_output_predict.txt)
y_predict = model.predict(x_test).round()

for i in range(10,20):
  print(x_test[100+i]," ",y_test[100+i]," ",y_predict[100+i])
  print("\n")
# f = open("input_output_predict.txt", "w")
# n = y_test.size
# cnt = 0
# for i in range(0,n-1):
#     # f.write("[")
#     # count = 0
#     # for x in x_test[i]:
#     #     for j in x:
#     #       f.write(str(j)+",")
#     # f.write("];\t")
#     # f.write("["+str(y_test[i])+"];\t")
#     # f.write("["+str(y_predict[i])+"];\t \n")
#     ok=1
#     # print("hi")
#     # print(len(y_test[i]))
#     for  y,y_ex in zip(y_test[i],y_predict[i]):
#       if y!=y_ex:
#         ok=0
#     cnt+=ok
# f.write("Number of matches: "+str(cnt)+" out of " + str(n) +"\n")
# f.close()
# print("Number of matches: "+str(cnt)+" out of " + str(n) )
 

1453/1453 [==============================] - 2s 1ms/step
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]   [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]   [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]   [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]   [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]   [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]   [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 0 1 0 0]   [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]   [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


[0 0 0 