<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/Fixed%20Priority%20Arbiter/Fixed_Priority_32bit_99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# only for Google Colab compatibiity
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.9.2


In [ ]:
%matplotlib notebook

In [ ]:
df = pd.read_csv('fixed_pr_32_50k.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("fixed_pr_32_50k.txt",sep=" ",header=None, dtype=col_str_dic)
x_gen = df.iloc[:,0]
y_gen = df.iloc[:,1]
x_samples=[]
y_samples=[]
for x in x_gen:
  temp = list(x)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  x_samples.append(temp_list)
for y in y_gen:
  temp = list(y)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  y_samples.append(temp_list)

In [ ]:
# #print("x_samples = input_values() is called")
# x_samples = input_values()
# y_samples = output_values()
# #print("x_samples = input_values() is over")

In [ ]:
len(y_samples)

64866

In [ ]:
x = np.array(x_samples) # 16 inputs
print(x)
y = np.array(y_samples) # 16 ootput
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)
#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [ ]:
#ANN1
#model = models.Sequential(name='Parity_checker')
#model.add(layers.Input(shape=(32,), name='input'))
#model.add(layers.Dense(units=32,activation=activations.relu, name='hidden1'))
## model.add(layers.Dense(units=3, activation=activations.sigmoid, name='hidden2'))
#model.add(layers.Dense(units=1, activation=activations.sigmoid, name='output'))

#add the layers
#ANN2:0.99 accuracy
# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(64, input_dim=32, activation='relu'))
# model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# ANN3:0.99 accuracy
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='sigmoid'))

# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(32, input_dim=16, activation='relu'))
# # model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='relu'))
# model.add(tf.keras.layers.Dense(8, activation='relu'))
# model.add(tf.keras.layers.Dense(4, activation='relu'))
# model.add(tf.keras.layers.Dense(2, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                1056      
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dense_5 (Dense)             (None, 32)                1056      
                                                                 
Total params: 6,336
Trainable params: 6,336
Non-trainabl

In [ ]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [ ]:
model.fit(x_train, y_train, epochs=100)
score = model.evaluate(x_test, y_test, verbose=2)

Epoch 1/100
1419/1419 [==============================] - 5s 3ms/step - loss: 0.0126 - accuracy: 0.8056
Epoch 2/100
1419/1419 [==============================] - 4s 3ms/step - loss: 0.0020 - accuracy: 0.9416
Epoch 3/100
1419/1419 [==============================] - 4s 3ms/step - loss: 2.6433e-04 - accuracy: 0.9924
Epoch 4/100
1419/1419 [==============================] - 4s 3ms/step - loss: 2.7803e-04 - accuracy: 0.9934
Epoch 5/100
1419/1419 [==============================] - 4s 3ms/step - loss: 1.4138e-04 - accuracy: 0.9969
Epoch 6/100
1419/1419 [==============================] - 4s 3ms/step - loss: 1.0757e-04 - accuracy: 0.9977
Epoch 7/100
1419/1419 [==============================] - 4s 3ms/step - loss: 8.3070e-05 - accuracy: 0.9983
Epoch 8/100
1419/1419 [==============================] - 4s 3ms/step - loss: 7.5356e-05 - accuracy: 0.9985
Epoch 9/100
1419/1419 [==============================] - 4s 3ms/step - loss: 5.0594e-05 - accuracy: 0.9988
Epoch 10/100
1419/1419 [=====================

In [ ]:
#Comparing the data and writing into the file ( input_output_predict.txt)
y_predict = model.predict(x_test).round()

print(x_test[100]," ",y_test[100]," ",y_predict[100])
# f = open("input_output_predict.txt", "w")
# n = y_test.size
# cnt = 0
# for i in range(0,n-1):
#     # f.write("[")
#     # count = 0
#     # for x in x_test[i]:
#     #     for j in x:
#     #       f.write(str(j)+",")
#     # f.write("];\t")
#     # f.write("["+str(y_test[i])+"];\t")
#     # f.write("["+str(y_predict[i])+"];\t \n")
#     ok=1
#     # print("hi")
#     # print(len(y_test[i]))
#     for  y,y_ex in zip(y_test[i],y_predict[i]):
#       if y!=y_ex:
#         ok=0
#     cnt+=ok
# f.write("Number of matches: "+str(cnt)+" out of " + str(n) +"\n")
# f.close()
# print("Number of matches: "+str(cnt)+" out of " + str(n) )
 

609/609 [==============================] - 1s 1ms/step
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0]   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0.]


In [ ]:
num_examples = 300000
num_classes = 32
test_len = num_examples*0.3
len2 = 12
#construct input values ,data set stored in the file: input_output_32_bit.txt 

def input_values():
    multiple_values = [map(int, '{0:020b}'.format(i)) for i in range(2 ** 20)]
    multiple_values2 = [map(int, '{0:020b}'.format(i)) for i in range(2 ** 20)]
    #f = open("input_output_32_bit.txt", "w")
    random.shuffle(multiple_values)
    random.shuffle(multiple_values2)		
    #multiple_values = np.hstack((multiple_values1, multiple_values2))	
    #print(len(multiple_values))
    final_values = []	
    #temp = []	
    Nfinal_values = []
    Ntemp = []

    f2 = open("New_input_32_bit.txt", "w")
    for i in range(num_examples):
      value1=multiple_values[i]
      value2=multiple_values2[i]
      # number1=[]
      # number2=[]
      # number=[]
      temp = []
      parity = 0
      f2.write("[")
      for j in value1:
        #number1.append(j)
        temp.append([j]) 
        parity^=j
        f2.write(str(j)+",")
        
      loop = 0 
      for k in value2:
        #number2.append(k)
        temp.append([k])
        parity^=k 
        f2.write(str(k)+",")
        loop = loop + 1
        if loop == len2:
         break  


      f2.write("],\t")
      f2.write("["+str(parity)+"]\t"+"\n")
      final_values.append(temp)
    f2.close
    #print(final_values)
    return final_values

    
#calculate output values
def output_values(inputs):
    final_values = []
    for value in inputs:
        # output_values = [0 for _ in range(num_classes)]
        count = 0
        for i in value:
            count ^= i[0]
        # if count < num_classes:
            # output_values[count] = 1
        final_values.append([count])
    return final_values
