<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/Fixed%20Priority%20Arbiter/Fixed_priority_16bit_git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
# only for Google Colab compatibiity
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [39]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.11.0


In [40]:
%matplotlib notebook

In [41]:
df = pd.read_csv('fread.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("fread.txt",sep=" ",header=None, dtype=col_str_dic)
x_gen = df.iloc[:,0]
y_gen = df.iloc[:,1]
x_samples=[]
y_samples=[]
for x in x_gen:
  temp = list(x)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  x_samples.append(temp_list)
for y in y_gen:
  temp = list(y)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  y_samples.append(temp_list)

In [42]:
# #print("x_samples = input_values() is called")
# x_samples = input_values()
# y_samples = output_values()
# #print("x_samples = input_values() is over")

In [43]:
len(y_samples)

65536

In [44]:
x = np.array(x_samples) # 16 inputs
print(x)
y = np.array(y_samples) # 16 ootput
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)
#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [46]:
#ANN1
#model = models.Sequential(name='Parity_checker')
#model.add(layers.Input(shape=(32,), name='input'))
#model.add(layers.Dense(units=32,activation=activations.relu, name='hidden1'))
## model.add(layers.Dense(units=3, activation=activations.sigmoid, name='hidden2'))
#model.add(layers.Dense(units=1, activation=activations.sigmoid, name='output'))

#add the layers
#ANN2:0.99 accuracy
# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(64, input_dim=32, activation='relu'))
# model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# ANN3:0.99 accuracy
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(16, input_dim=16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(32, input_dim=16, activation='relu'))
# # model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='relu'))
# model.add(tf.keras.layers.Dense(8, activation='relu'))
# model.add(tf.keras.layers.Dense(4, activation='relu'))
# model.add(tf.keras.layers.Dense(2, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 16)                272       
                                                                 
 dense_19 (Dense)            (None, 16)                272       
                                                                 
 dense_20 (Dense)            (None, 16)                272       
                                                                 
 dense_21 (Dense)            (None, 16)                272       
                                                                 
 dense_22 (Dense)            (None, 16)                272       
                                                                 
 dense_23 (Dense)            (None, 16)                272       
                                                                 
Total params: 1,632
Trainable params: 1,632
Non-traina

In [47]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [48]:
model.fit(x_train, y_train, epochs=50)
score = model.evaluate(x_test, y_test, verbose=2)

Epoch 1/50
1434/1434 [==============================] - 8s 4ms/step - loss: 0.0232 - accuracy: 0.7984
Epoch 2/50
1434/1434 [==============================] - 5s 3ms/step - loss: 0.0020 - accuracy: 0.9696
Epoch 3/50
1434/1434 [==============================] - 6s 4ms/step - loss: 0.0019 - accuracy: 0.9696
Epoch 4/50
1434/1434 [==============================] - 5s 4ms/step - loss: 0.0019 - accuracy: 0.9696
Epoch 5/50
1434/1434 [==============================] - 5s 3ms/step - loss: 0.0019 - accuracy: 0.9696
Epoch 6/50
1434/1434 [==============================] - 6s 4ms/step - loss: 0.0020 - accuracy: 0.9698
Epoch 7/50
1434/1434 [==============================] - 5s 4ms/step - loss: 0.0017 - accuracy: 0.9773
Epoch 8/50
1434/1434 [==============================] - 6s 4ms/step - loss: 0.0014 - accuracy: 0.9773
Epoch 9/50
1434/1434 [==============================] - 5s 4ms/step - loss: 0.0015 - accuracy: 0.9775
Epoch 10/50
1434/1434 [==============================] - 6s 4ms/step - loss: 0.001

In [49]:
#Comparing the data and writing into the file ( input_output_predict.txt)
y_predict = model.predict(x_test).round()

print(x_test[100]," ",y_test[100]," ",y_predict[100]) 

615/615 [==============================] - 1s 1ms/step
[0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0]   [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
