<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/ML-Based-Output-Prediction-of-RTL-Model%20/APB%201%20Master%202%20Slaves/APB_9May23_PSel_PEnabl_RisingEdge_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Predict Rising Edge of PENABLE by depending on PSEL1, PSEL2 
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.12.0


In [ ]:
%matplotlib notebook

In [ ]:
#HandShake Testing Data *****************************
df = pd.read_csv('apb6.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("apb6.txt",sep=" ",header=None, dtype=col_str_dic)
x0 = df.iloc[:,0]
x1 = df.iloc[:,1]
x2 = df.iloc[:,2]
k = 0
for x in x0:
  k = k+1

#new data start

x3_samples=[]
y3_samples=[]

y4_samples=[]

for i in range(0,k-2):
  temp = list(x0[i])
  temp_list=[]
  temp_list_y=[]
#'''
  if x0[i]=="1" and x0[i+1]=="0":
    #print(x0[i],x1[i])
    #print(x0[i+1],x1[i+1]) 
    #print("Falling edge of Valid")
    y4_samples.append(1)
  else:
    y4_samples.append(0)
#'''
  for c0 in temp:
    if c0=="x":
      print("c0=",c0)
      temp_list.append(int(2))
    else:
      #print("c0!=X")
      temp_list.append(int(c0))
    '''
    if c0=="1":
      print("c0=",c0)
    else:
      print("c0!=1")
    '''
    #temp_list_y.append(int(c0))
  temp = list(x1[i])
  for c1 in temp:
    if c1=="x":
      #print("c0=",c0)
      temp_list.append(int(2))
    else:
      temp_list.append(int(c1))
    
  temp = list(x2[i])
  for c2 in temp:
    temp_list.append(int(c2))
  x3_samples.append(temp_list)
  #y3_samples.append(temp_list_y)

for i in range(1,k-1):
  temp = list(x2[i])
  temp_list_y=[]
  for c2 in temp:
    temp_list_y.append(int(c2))
  y3_samples.append(temp_list_y)

print("*********New Data***")
len(x3_samples)
print("x3_samples=",len(x3_samples),x3_samples)
print("y3_samples=",len(y3_samples),y3_samples)
#print("y4_samples=",len(y4_samples),y4_samples)
print("************")
#numpy array start
x_temp = np.array(x3_samples) 
x_t = []
for a in x_temp:
  temp = a.flatten()
  x_t.append(temp)
x4 = np.array(x_t)
print("x4=",len(x4),x4)

'''
y5_temp = np.array(y4_samples) 
y5_t = []
for a in y5_temp:
  temp = a.flatten()
  y5_t.append(temp)
y5 = np.array(y5_t)
print("y5=",len(y5),y5)
'''
y_temp = np.array(y3_samples) 
y_t = []
for a in y_temp:
  temp = a.flatten()
  y_t.append(temp)
y4 = np.array(y_t)
print("y4=",len(y4),y4)
#numpy array end

#new data end


c0= x
*********New Data***
x3_samples= 4992 [[0, 0, 0], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 1], [0, 0, 0], [2, 2, 0], [0, 0, 0], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1]

In [ ]:

from sklearn.model_selection import train_test_split
#x1_train, x1_test, y1_train, y1_test = train_test_split(x4, y4, test_size=0.3, shuffle=False)
x1_train, x1_test, y1_train, y1_test = train_test_split(x4, y4, test_size=0.3, shuffle=False)

#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [ ]:
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Dense(6, input_dim=3, activation='relu'))
#model.add(tf.keras.layers.Dense(4, activation='relu'))
#model.add(tf.keras.layers.Dense(4, activation='relu'))
#model.add(tf.keras.layers.Dense(4, activation='relu'))
model1.add(tf.keras.layers.Dense(3, activation='relu'))
model1.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 24        
                                                                 
 dense_1 (Dense)             (None, 3)                 21        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model1.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
#model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [ ]:
model1.fit(x1_train, y1_train, epochs=10)
score = model1.evaluate(x1_test, y1_test, verbose=2)

Epoch 1/10
110/110 [==============================] - 6s 3ms/step - loss: 0.2566 - accuracy: 0.4980
Epoch 2/10
110/110 [==============================] - 0s 3ms/step - loss: 0.2111 - accuracy: 0.7132
Epoch 3/10
110/110 [==============================] - 0s 3ms/step - loss: 0.1653 - accuracy: 0.9946
Epoch 4/10
110/110 [==============================] - 0s 3ms/step - loss: 0.1314 - accuracy: 0.9937
Epoch 5/10
110/110 [==============================] - 0s 3ms/step - loss: 0.1058 - accuracy: 0.9960
Epoch 6/10
110/110 [==============================] - 0s 3ms/step - loss: 0.0865 - accuracy: 0.9986
Epoch 7/10
110/110 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9986
Epoch 8/10
110/110 [==============================] - 0s 3ms/step - loss: 0.0610 - accuracy: 0.9986
Epoch 9/10
110/110 [==============================] - 0s 3ms/step - loss: 0.0522 - accuracy: 0.9986
Epoch 10/10
110/110 [==============================] - 0s 3ms/step - loss: 0.0452 - accuracy: 0.9986

In [ ]:
#Comparing the data and writing into the file ( predict.txt)
y_predict = model1.predict(x1_test).round()
length=len(y_predict)
f = open("apb_predict.txt", "w")
for i in range(0,length):
  print(x1_test[i]," ",y1_test[i]," ", y_predict[i])
  #print(x1_test[i][0]," ",x1_test[i][1])
  f.write(str(x1_test[i])+" "+str(y1_test[i])+" "+str(y_predict[i])+"\n")
  #f.write(" ")
  print("\n")
f.close()

47/47 [==============================] - 0s 1ms/step
[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0 0]   [1]   [1.]


[1 0 1]   [0]   [0.]


[1 0