<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/Shift%20Register/32%20Bit/Shift_Register_32bit_Git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# only for Google Colab compatibiity
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.11.0


In [3]:
%matplotlib notebook

In [4]:
df = pd.read_csv('shift_32bit.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("shift_32bit.txt",sep=" ",header=None, dtype=col_str_dic)
x_clk = df.iloc[:,0]
x_bit = df.iloc[:,1]
y_gen = df.iloc[:,2]
x_samples=[]
y_samples=[]
k = 0
for x in x_bit:
  k = k+1

temp = list(x_clk[0])
temp_list=[]
for c in temp:
  temp_list.append(int(c))
temp = list(x_bit[0])
for c in temp:
  temp_list.append(int(c))
temp = list(y_gen[0])
for c in temp:
  temp_list.append(int(c))
x_samples.append(temp_list)

for i in range(1,k):
  temp = list(x_clk[i])
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  temp = list(x_bit[i])
  for c in temp:
    temp_list.append(int(c))
  temp = list(y_gen[i-1])
  for c in temp:
    temp_list.append(int(c))
  x_samples.append(temp_list)


for y in y_gen:
  # print(y)
  temp = list(y)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  y_samples.append(temp_list)

print(x_samples[2])
print(y_samples[2])

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [5]:
x_s = []
y_s = []
# k = len(x_samples)
# temp =[]
# temp.append(x_samples[0])
# temp.append(x_samples[0])
# x_s.append(temp)
# for i in range(1,k):
#   temp = []
#   temp.append(y_samples[i-1])
#   temp.append(x_samples[i])
#   x_s.append(temp)
y_s = y_samples
x_s = x_samples
print(x_s[2])
print(y_s[2])

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [6]:
len(y_s)

49997

In [7]:
x_temp = np.array(x_s) # 16 inputs
x_t = []
for a in x_temp:
  temp = a.flatten()
  x_t.append(temp)
x = np.array(x_t)
print(x[2])
y_temp = np.array(y_s) # 16 inputs
y_t = []
for a in y_temp:
  temp = a.flatten()
  y_t.append(temp)
y = np.array(y_t)
print(y[2])

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)
#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [9]:
#ANN1
#model = models.Sequential(name='Parity_checker')
#model.add(layers.Input(shape=(32,), name='input'))
#model.add(layers.Dense(units=32,activation=activations.relu, name='hidden1'))
## model.add(layers.Dense(units=3, activation=activations.sigmoid, name='hidden2'))
#model.add(layers.Dense(units=1, activation=activations.sigmoid, name='output'))

#add the layers
#ANN2:0.99 accuracy
# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(64, input_dim=32, activation='relu'))
# model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# ANN3:0.99 accuracy
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(34, input_dim=34, activation='relu'))
model.add(tf.keras.layers.Dense(34, activation='relu'))
model.add(tf.keras.layers.Dense(34, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
#model.add(tf.keras.layers.Dense(9, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='sigmoid'))

# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(32, input_dim=16, activation='relu'))
# # model.add(tf.keras.layers.Dense(32, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='relu'))
# model.add(tf.keras.layers.Dense(8, activation='relu'))
# model.add(tf.keras.layers.Dense(4, activation='relu'))
# model.add(tf.keras.layers.Dense(2, activation='relu'))
# model.add(tf.keras.layers.Dense(16, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 34)                1190      
                                                                 
 dense_1 (Dense)             (None, 34)                1190      
                                                                 
 dense_2 (Dense)             (None, 34)                1190      
                                                                 
 dense_3 (Dense)             (None, 32)                1120      
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dense_5 (Dense)             (None, 32)                1056      
                                                                 
Total params: 6,802
Trainable params: 6,802
Non-trainabl

In [10]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [11]:
model.fit(x_train, y_train, epochs=200)
score = model.evaluate(x_test, y_test, verbose=2)

Epoch 1/200
1094/1094 [==============================] - 12s 4ms/step - loss: 0.0153 - accuracy: 0.0000e+00
Epoch 2/200
1094/1094 [==============================] - 4s 4ms/step - loss: 2.5869e-04 - accuracy: 5.7148e-05
Epoch 3/200
1094/1094 [==============================] - 4s 4ms/step - loss: 2.3949e-04 - accuracy: 0.0075
Epoch 4/200
1094/1094 [==============================] - 4s 4ms/step - loss: 1.9180e-04 - accuracy: 0.1566
Epoch 5/200
1094/1094 [==============================] - 4s 3ms/step - loss: 1.4939e-04 - accuracy: 0.0132
Epoch 6/200
1094/1094 [==============================] - 4s 4ms/step - loss: 1.0817e-04 - accuracy: 5.7148e-04
Epoch 7/200
1094/1094 [==============================] - 4s 4ms/step - loss: 8.3242e-05 - accuracy: 0.0065
Epoch 8/200
1094/1094 [==============================] - 4s 3ms/step - loss: 7.9852e-05 - accuracy: 5.1433e-04
Epoch 9/200
1094/1094 [==============================] - 4s 4ms/step - loss: 6.4696e-05 - accuracy: 0.0194
Epoch 10/200
1094/1094 [

In [12]:
#Comparing the data and writing into the file ( input_output_predict.txt)
y_predict = model.predict(x_test).round()

for i in range(10,20):
  print(x_test[i]," ",y_test[i]," ",y_predict[i])
  print("\n")
# f = open("input_output_predict.txt", "w")
# n = y_test.size
# cnt = 0
# for i in range(0,n-1):
#     # f.write("[")
#     # count = 0
#     # for x in x_test[i]:
#     #     for j in x:
#     #       f.write(str(j)+",")
#     # f.write("];\t")
#     # f.write("["+str(y_test[i])+"];\t")
#     # f.write("["+str(y_predict[i])+"];\t \n")
#     ok=1
#     # print("hi")
#     # print(len(y_test[i]))
#     for  y,y_ex in zip(y_test[i],y_predict[i]):
#       if y!=y_ex:
#         ok=0
#     cnt+=ok
# f.write("Number of matches: "+str(cnt)+" out of " + str(n) +"\n")
# f.close()
# print("Number of matches: "+str(cnt)+" out of " + str(n) )
 

469/469 [==============================] - 1s 2ms/step
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]   [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 1.]


[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]   [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 1.]


[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]   [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 1.]


[0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]   [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]   [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1.