<a href="https://colab.research.google.com/github/surajitdas2030/ML-Based-Output-Prediction-of-RTL-Model/blob/main/TrainedModel_ShiftReg/Get_weight_Shift_Register_8bit_Github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# only for Google Colab compatibiity
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, activations
import random
print(tf.__version__)
np.random.seed(0)
tf.random.set_seed(0)

2.12.0


In [15]:
%matplotlib notebook

In [16]:
df = pd.read_csv('shift.txt',sep=" ",header=None)
col_str_dic = {column:str for column in list(df)}
df = pd.read_csv("shift.txt",sep=" ",header=None, dtype=col_str_dic)
x_clk = df.iloc[:,0]
x_bit = df.iloc[:,1]
y_gen = df.iloc[:,2]
x_samples=[]
y_samples=[]
k = 0
for x in x_bit:
  k = k+1

temp = list(x_clk[0])
temp_list=[]
for c in temp:
  temp_list.append(int(c))
temp = list(x_bit[0])
for c in temp:
  temp_list.append(int(c))
temp = list(y_gen[0])
for c in temp:
  temp_list.append(int(c))
x_samples.append(temp_list)

for i in range(1,k):
  temp = list(x_clk[i])
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  temp = list(x_bit[i])
  for c in temp:
    temp_list.append(int(c))
  temp = list(y_gen[i-1])
  for c in temp:
    temp_list.append(int(c))
  x_samples.append(temp_list)


for y in y_gen:
  # print(y)
  temp = list(y)
  temp_list=[]
  for c in temp:
    temp_list.append(int(c))
  y_samples.append(temp_list)

print(x_samples[2])
print(y_samples[2])

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0]


In [17]:
x_s = []
y_s = []
# k = len(x_samples)
# temp =[]
# temp.append(x_samples[0])
# temp.append(x_samples[0])
# x_s.append(temp)
# for i in range(1,k):
#   temp = []
#   temp.append(y_samples[i-1])
#   temp.append(x_samples[i])
#   x_s.append(temp)
y_s = y_samples
x_s = x_samples
print(x_s[2])
print(y_s[2])

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0]


In [18]:
len(y_s)

10421

In [19]:
x_temp = np.array(x_s) # 16 inputs
x_t = []
for a in x_temp:
  temp = a.flatten()
  x_t.append(temp)
x = np.array(x_t)
print(x[2])
y_temp = np.array(y_s) # 16 inputs
y_t = []
for a in y_temp:
  temp = a.flatten()
  y_t.append(temp)
y = np.array(y_t)
print(y[2])

[1 1 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]


In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)
#x_train, x_test, y_train, y_test = train_test_split(x_samples, y_samples, test_size=0.3, shuffle=True)

In [21]:
layers=3
inputs=10
neurons_l0=10
neurons_l1=10
neurons_l2=8

# ANN3:0.99 accuracy
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, input_dim=10, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='relu'))
model.add(tf.keras.layers.Dense(8, activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 8)                 88        
                                                                 
Total params: 308
Trainable params: 308
Non-trainable params: 0
_________________________________________________________________


In [22]:
#model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
weight1 = model.get_weights()
print("weight1")
print(weight1)

weight1
[array([[-0.15436366, -0.11579472, -0.46121883, -0.5341646 , -0.533273  ,
         0.32213116, -0.0159443 ,  0.11680561, -0.15469638, -0.13228828],
       [-0.05351323,  0.2950412 ,  0.09340656,  0.46987367, -0.02976435,
        -0.4080215 ,  0.5203922 ,  0.19622368,  0.26016462,  0.18883252],
       [-0.54599845,  0.20735258,  0.02260256, -0.5439447 , -0.42998526,
         0.5241455 , -0.47153705, -0.32724157,  0.5261698 , -0.03738832],
       [ 0.17259753,  0.44076276,  0.3532527 , -0.4179937 ,  0.28868318,
         0.25607306, -0.22589687,  0.33387524, -0.40996426,  0.17921752],
       [-0.14130637,  0.31612295, -0.35564756, -0.06175289, -0.41843298,
         0.20139867,  0.4085192 , -0.01769614, -0.21693778, -0.4708913 ],
       [ 0.22381568,  0.5014857 , -0.5170348 , -0.515724  , -0.27558726,
         0.36676484, -0.51898307,  0.08665037, -0.47776243,  0.13622731],
       [ 0.53868103,  0.27408862, -0.23386645, -0.02296805,  0.01346785,
         0.29991096,  0.49165177,  0

Comparing the data and writing into the file ( **input_output_predict.txt**)

Here the
*  **x_text** is the input sample data
*  **y_text** is the expected output data
*  **y_predict** is predicted output data


In [23]:
model.fit(x_train, y_train, epochs=180)
weight2 = model.get_weights()
print("weight2")
print(weight2)
weight_l1 = model.layers[0].get_weights()[0]
weight_l1_b = model.layers[0].get_weights()[1]
weight_l2 = model.layers[1].get_weights()[0]
weight_l2_b = model.layers[1].get_weights()[1]
weight_l3 = model.layers[2].get_weights()[0]
weight_l3_b = model.layers[2].get_weights()[1]
f1 = open("ann_weight_shift8.txt", "w")
f1.write("#layers"+"\n"+str(layers)+"\n")
f1.write("#inputs"+"\n"+str(inputs)+"\n")
f1.write("#neurons_L1"+"\n"+str(neurons_l0)+"\n")
f1.write("#neurons_L2"+"\n"+str(neurons_l1)+"\n")
f1.write("#neurons_L3"+"\n"+str(neurons_l2)+"\n")

f1.write("#L1_wt"+"\n")
for i in range(0,10):
  f1.write(str(weight_l1[i][0])+"\b"+str(weight_l1[i][1])+"\b"+str(weight_l1[i][2])+"\b"+str(weight_l1[i][3])+"\b"+str(weight_l1[i][4])+"\b"+str(weight_l1[i][5])+"\b"+str(weight_l1[i][6])+"\b"+str(weight_l1[i][7])+"\b"+str(weight_l1[i][8])+"\b"+str(weight_l1[i][9])+"\n")


f1.write("#L1_b"+"\n")
#for i in range(0,10):
 #   f1.write(str(weight_l1_b[i])+"\b")
#f1.write("\n")
f1.write(str(weight_l1_b[0])+"\b"+str(weight_l1_b[1])+"\b"+str(weight_l1_b[2])+"\b"+str(weight_l1_b[3])+"\b"+str(weight_l1_b[4])+"\b"+str(weight_l1_b[5])+"\b"+str(weight_l1_b[6])+"\b"+str(weight_l1_b[7])+"\b"+str(weight_l1_b[8])+"\b"+str(weight_l1_b[9])+"\n")

f1.write("#L2_wt"+"\n")
for i in range(0,10):
  f1.write(str(weight_l2[i][0])+"\b"+str(weight_l2[i][1])+"\b"+str(weight_l2[i][2])+"\b"+str(weight_l2[i][3])+"\b"+str(weight_l2[i][4])+"\b"+str(weight_l2[i][5])+"\b"+str(weight_l2[i][6])+"\b"+str(weight_l2[i][7])+"\b"+str(weight_l2[i][8])+"\b"+str(weight_l2[i][9])+"\n")
'''
  for j in range(0,10):
    f1.write(str(weight_l2[i][j])+"\b")
  f1.write("\n")
'''


f1.write("#L2_b"+"\n")
'''
for i in range(0,10):
  f1.write(str(weight_l2_b[i])+"\b")
f1.write("\n")
'''
f1.write(str(weight_l2_b[0])+"\b"+str(weight_l2_b[1])+"\b"+str(weight_l2_b[2])+"\b"+str(weight_l2_b[3])+"\b"+str(weight_l2_b[4])+"\b"+str(weight_l2_b[5])+"\b"+str(weight_l2_b[6])+"\b"+str(weight_l2_b[7])+"\b"+str(weight_l2_b[8])+"\b"+str(weight_l2_b[9])+"\n")

f1.write("#L3_wt"+"\n")
for i in range(0,10):
  f1.write(str(weight_l3[i][0])+"\b"+str(weight_l3[i][1])+"\b"+str(weight_l3[i][2])+"\b"+str(weight_l3[i][3])+"\b"+str(weight_l3[i][4])+"\b"+str(weight_l3[i][5])+"\b"+str(weight_l3[i][6])+"\b"+str(weight_l3[i][7])+"\n")
#  for j in range(0,8):
#    f1.write(str(weight_l3[i][j])+"\b")
#  f1.write("\n")


f1.write("#L3_b"+"\n")
#for i in range(0,8):
#  f1.write(str(weight_l3_b[i])+"\b")
#f1.write("\n")
f1.write(str(weight_l3_b[0])+"\b"+str(weight_l3_b[1])+"\b"+str(weight_l3_b[2])+"\b"+str(weight_l3_b[3])+"\b"+str(weight_l3_b[4])+"\b"+str(weight_l3_b[5])+"\b"+str(weight_l3_b[6])+"\b"+str(weight_l3_b[7])+"\n")

f1.write("#end\n#end\n")

f1.close()
########
score = model.evaluate(x_test, y_test, verbose=2)

Epoch 1/180
228/228 [==============================] - 2s 3ms/step - loss: 0.2308 - accuracy: 0.1756
Epoch 2/180
228/228 [==============================] - 1s 3ms/step - loss: 0.1075 - accuracy: 0.2488
Epoch 3/180
228/228 [==============================] - 1s 3ms/step - loss: 0.0231 - accuracy: 0.2487
Epoch 4/180
228/228 [==============================] - 1s 3ms/step - loss: 0.0065 - accuracy: 0.2490
Epoch 5/180
228/228 [==============================] - 1s 3ms/step - loss: 0.0029 - accuracy: 0.2492
Epoch 6/180
228/228 [==============================] - 1s 3ms/step - loss: 0.0017 - accuracy: 0.2492
Epoch 7/180
228/228 [==============================] - 1s 3ms/step - loss: 0.0011 - accuracy: 0.2494
Epoch 8/180
228/228 [==============================] - 1s 3ms/step - loss: 7.8239e-04 - accuracy: 0.2494
Epoch 9/180
228/228 [==============================] - 1s 3ms/step - loss: 6.3387e-04 - accuracy: 0.2494
Epoch 10/180
228/228 [==============================] - 1s 3ms/step - loss: 5.4841e

In [24]:
#Comparing the data and writing into the file ( input_output_predict.txt)
y_predict = model.predict(x_test).round()

for i in range(10,20):
  print(x_test[i]," ",y_test[i]," ",y_predict[i])
  print("\n")
# f = open("input_output_predict.txt", "w")
# n = y_test.size
# cnt = 0
# for i in range(0,n-1):
#     # f.write("[")
#     # count = 0
#     # for x in x_test[i]:
#     #     for j in x:
#     #       f.write(str(j)+",")
#     # f.write("];\t")
#     # f.write("["+str(y_test[i])+"];\t")
#     # f.write("["+str(y_predict[i])+"];\t \n")
#     ok=1
#     # print("hi")
#     # print(len(y_test[i]))
#     for  y,y_ex in zip(y_test[i],y_predict[i]):
#       if y!=y_ex:
#         ok=0
#     cnt+=ok
# f.write("Number of matches: "+str(cnt)+" out of " + str(n) +"\n")
# f.close()
# print("Number of matches: "+str(cnt)+" out of " + str(n) )


98/98 [==============================] - 0s 1ms/step
[0 1 0 1 0 1 0 1 0 1]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


[0 0 1 0 1 0 1 0 1 0]   [1 0 1 0 1 0 1 0]   [1. 0. 1. 0. 1. 0. 1. 0.]


[0 1 0 1 0 1 0 1 0 1]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


[1 0 1 0 1 0 1 0 1 0]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


[1 0 1 0 1 0 1 0 1 0]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


[1 0 1 0 1 0 1 0 1 0]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


[0 0 1 0 1 0 1 0 1 0]   [1 0 1 0 1 0 1 0]   [1. 0. 1. 0. 1. 0. 1. 0.]


[0 0 1 0 1 0 1 0 1 0]   [1 0 1 0 1 0 1 0]   [1. 0. 1. 0. 1. 0. 1. 0.]


[0 0 1 0 1 0 1 0 1 0]   [1 0 1 0 1 0 1 0]   [1. 0. 1. 0. 1. 0. 1. 0.]


[0 1 0 1 0 1 0 1 0 1]   [0 1 0 1 0 1 0 1]   [0. 1. 0. 1. 0. 1. 0. 1.]


